name: Swift Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        xcode: [15.4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10.0"

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
